# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :test do
    # add actions here: https://docs.fastlane.tools/actions

    build_number = increment_build_number(xcodeproj: "TestFastlane.xcodeproj")

    commit_version_bump(
      message: 'Build Version Bump by fastlane',
      xcodeproj: "TestFastlane.xcodeproj",
      force: true
    )

    push_to_git_remote

    build_ios_app(
      export_xcargs: "-allowProvisioningUpdates"
    )

    # push_to_git_remote(remote: "origin", local_branch: "HEAD", remote_branch: "master", force: true, tags: true)

    upload_to_testflight


  end
end
